#!/bin/bash
# refresh_from_mac.sh
# Copies configs from Mac to this dotfiles repo
# This should only be run on Mac to update the repo with current configs

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$SCRIPT_DIR/.config"

echo "Refreshing dotfiles from Mac..."

# Create directory structure
mkdir -p "$CONFIG_DIR/yazi/plugins"
mkdir -p "$CONFIG_DIR/zellij/layouts"

# Copy Yazi configs
echo "Copying Yazi configs..."
cp "$HOME/.config/yazi/init.lua" "$CONFIG_DIR/yazi/init.lua"
cp "$HOME/.config/yazi/keymap.toml" "$CONFIG_DIR/yazi/keymap.toml"
cp "$HOME/.config/yazi/yazi.toml" "$CONFIG_DIR/yazi/yazi.toml"
cp "$HOME/.config/yazi/theme.toml" "$CONFIG_DIR/yazi/theme.toml"

# Copy Zellij configs
echo "Copying Zellij configs..."
cp "$HOME/.config/zellij/config.kdl" "$CONFIG_DIR/zellij/config.kdl"
cp "$HOME/.config/zellij/layouts/default.kdl" "$CONFIG_DIR/zellij/layouts/default.kdl"

# Now sanitize the copied configs for Linux
echo "Sanitizing zellij configs..."
# Remove autogenerated comment with personal path
sed -i.bak 's|// THIS FILE WAS AUTOGENERATED BY ZELLIJ.*|// Zellij configuration|g' "$CONFIG_DIR/zellij/config.kdl"
sed -i.bak '/\.config\/zellij\/config\.kdl\.bak/d' "$CONFIG_DIR/zellij/config.kdl"
rm -f "$CONFIG_DIR/zellij/config.kdl.bak"
echo "Sanitizing configs for Linux..."

# Sanitize yazi init.lua - replace Sublime Text path with $EDITOR
sed -i.bak 's|/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl|\$EDITOR|g' "$CONFIG_DIR/yazi/init.lua"
rm -f "$CONFIG_DIR/yazi/init.lua.bak"

# Sanitize yazi keymap.toml - replace subl with nvim (no GUI editor on Linux)
sed -i.bak "s|subl|nvim|g" "$CONFIG_DIR/yazi/keymap.toml"
rm -f "$CONFIG_DIR/yazi/keymap.toml.bak"

# Sanitize yazi theme.toml - comment out catppuccin theme
sed -i.bak 's|^\[flavor\]|# Optional: Install catppuccin theme with:\n#   ya pkg add yazi-rs/flavors:catppuccin-mocha\n# Then uncomment:\n# [flavor]|' "$CONFIG_DIR/yazi/theme.toml"
sed -i.bak 's|^dark = |# dark = |' "$CONFIG_DIR/yazi/theme.toml"
rm -f "$CONFIG_DIR/yazi/theme.toml.bak"

# Sanitize yazi yazi.toml - replace Mac-specific commands
# Replace 'open -a "Brave Browser"' with xdg-open
sed -i.bak 's|open -a "Brave Browser"|xdg-open|g' "$CONFIG_DIR/yazi/yazi.toml"
sed -i.bak 's|open -a skim|xdg-open|g' "$CONFIG_DIR/yazi/yazi.toml"
# Replace macOS 'open' commands with xdg-open
sed -i.bak 's|{ run = '\''open "\$@"'\'', *desc = "Open", for = "macos" }|{ run = '\''xdg-open "\$@"'\'', desc = "Open", for = "linux" }|g' "$CONFIG_DIR/yazi/yazi.toml"
sed -i.bak 's|{ run = '\''open -R "\$1"'\''|{ run = '\''xdg-open "$(dirname "\$1")"'\''|g' "$CONFIG_DIR/yazi/yazi.toml"
# Remove subl opener entirely and replace all subl references with edit
# No Sublime Text on Linux - use nvim via the 'edit' opener
sed -i.bak '/^subl = \[/,/^\]/d' "$CONFIG_DIR/yazi/yazi.toml"
sed -i.bak 's/"subl"/"edit"/g' "$CONFIG_DIR/yazi/yazi.toml"
sed -i.bak "s|run = 'subl|run = 'nvim|g" "$CONFIG_DIR/yazi/yazi.toml"
# Remove duplicate "edit" entries from use arrays
sed -i.bak 's/"edit", "edit"/"edit"/g' "$CONFIG_DIR/yazi/yazi.toml"
rm -f "$CONFIG_DIR/yazi/yazi.toml.bak"

echo "Done! Configs have been copied and sanitized for Linux."
echo "You can now commit these changes to the repo."
