[[input.prepend_keymap]]
on   = [ "<Esc>" ]
run = "close"
desc = "Cancel input"


[[manager.prepend_keymap]]
on   = [ "l" ]
run = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on   = [ "<Enter>" ]
run = "open --interactive"
desc = "Open the selected files interactively"

[[manager.prepend_keymap]]
on = [ "D" ]
run = ["remove --force"]
desc = "Move the files to the trash"


[[manager.prepend_keymap]]
on   = [ "/" ]
run = "filter --smart"
desc = "Filter the files"

[[manager.prepend_keymap]]
on   = [ "f" ]
run = "find --smart"
desc = "Find the files"

[[manager.prepend_keymap]]
on   = [ "<C-l>" ]
run = """  shell --confirm 'subl "$@"'  """
desc = "Open file in sublime text"

[[manager.prepend_keymap]]
on = [ "<C-n>" ]
run = '''
         shell 'ripdrag "$@" -x 2>/dev/null &' --confirm
         ''' 
desc = "activate ripdrag thing"

[[manager.prepend_keymap]]
on = [ "<C-k>" ]
run = "seek -5"
desc = "Seek up 5 units in the preview"

[[manager.prepend_keymap]]
on = [ "<C-j>" ]
run = "seek 5"
desc = "Seek down 5 units in the preview"

[[manager.prepend_keymap]]
on   = [ "<A-s>" ]
run = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[manager.prepend_keymap]]
on = [ "g", "b" ]
run = "cd ~/bin"
desc = "Go to the bin directory"

[[manager.prepend_keymap]]
on = [ "g", "j" ]
run = "cd /Volumes/t7/projects"
desc = "Go to the projects directory"

[[manager.prepend_keymap]]
on = [ "g", "d" ]
run = "cd /Volumes/t7/dls"
desc = "Go to the dls directory"

[[manager.prepend_keymap]]
on = [ "g", "n" ]
run = "cd /Volumes/t7/notes"
desc = "Go to the notes directory"

[[manager.prepend_keymap]]
on = [ "g", "f" ]
run = "cd /Volumes/t7/folders"
desc = "Go to the folders directory"

# [[manager.prepend_keymap]]
# on = [ "r" ]  
# run = "rename"
# run = 'nvim "$@" --block'
# desc = "Rename a file or directory"

# [[manager.prepend_keymap]]
# on = [ "q" ]
# run = "plugin projects --args=quit"
# desc = "Save last project and exit the process"

[[manager.prepend_keymap]]
on = [ "P", "s" ]
run = "plugin projects --args=save"
desc = "Save current project"

[[manager.prepend_keymap]]
on = [ "P", "l" ]
run = "plugin projects --args=load"
desc = "Load project"

[[manager.prepend_keymap]]
on = [ "P", "P" ]
run = "plugin projects --args=load_last"
desc = "Load last project"

[[manager.prepend_keymap]]
on = [ "P", "d" ]
run = "plugin projects --args=delete"
desc = "Delete project"

[[manager.prepend_keymap]]
on = [ "P", "D" ]
run = "plugin projects --args=delete_all"
desc = "Delete all projects"