[[mgr.prepend_keymap]]
on = ["f", "r"]
run = "plugin fr rg"
desc = "Search file by content (rg)"

[[mgr.prepend_keymap]]
on = ["f", "a"]
run = "plugin fr rga"
desc = "Search file by content (rga)"

######################

[[mgr.prepend_keymap]]
on   = [ "s" ]
run  = "search --via=fd --args='--hidden --no-ignore-vcs --no-ignore'"
desc = "Search files by name using fd"

[[mgr.prepend_keymap]]
on   = [ "S" ]
run  = "search --via=rg --args='--hidden --no-ignore'"
desc = "Search files by content using ripgrep"

[[mgr.prepend_keymap]]
on   = [ "Z" ]
run  = "plugin fzf"
desc = "Jump to a file/directory via fzf"

[[mgr.prepend_keymap]]
on   = [ "z" ]
run  = "plugin zoxide"
desc = "Jump to a directory via zoxide"


[[mgr.prepend_keymap]]
on = ["<C-r>"]
run = "refresh"
desc = "refresh the page "



[[input.prepend_keymap]]
on   = [ "<Esc>" ]
run = "close"
desc = "Cancel input"


[[mgr.prepend_keymap]]
on   = [ "d", "r" ]
run  = "plugin dragon"
desc = "Drag file(s) with dragon"

[[mgr.prepend_keymap]]
on   = [ "l" ]
run = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = [ "L" ]
run = "plugin --sync smart-open"
desc = "Open with system default"

[[mgr.prepend_keymap]]
on   = [ "<Enter>" ]
run = "open --interactive"
desc = "Open the selected files interactively"

[[mgr.prepend_keymap]]
on = [ "D" ]
run = ["remove --force"]
desc = "Move the files to the trash"


[[mgr.prepend_keymap]]
on   = [ "/" ]
run = "filter --smart"
desc = "Filter the files"

#[[manager.prepend_keymap]]
#on   = [ "/" ]
#run = "plugin smart-filter"
#desc = "Filter the files"


[[mgr.prepend_keymap]]
on   = [ "f" ]
run = "find --smart"
desc = "Find the files"


#[[manager.prepend_keymap]]
#on   = "p"
#run  = "plugin smart-paste"
#desc = "Paste into the hovered directory or CWD"

[[mgr.prepend_keymap]]
on   = [ "u" ]
run = """  shell --confirm 'nvim "$@"'  """
desc = "Open file in nvimime text"

[[mgr.prepend_keymap]]
on = [ "<C-n>" ]
run = '''
         shell 'ripdrag "$@" -x 2>/dev/null &' --confirm
         ''' 
desc = "activate ripdrag thing"

[[mgr.prepend_keymap]]
on = [ "<C-k>" ]
run = "seek -5"
desc = "Seek up 5 units in the preview"

[[mgr.prepend_keymap]]
on = [ "<C-j>" ]
run = "seek 5"
desc = "Seek down 5 units in the preview"

[[mgr.prepend_keymap]]
on   = [ "<A-s>" ]
run = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[mgr.prepend_keymap]]
on = [ "g", "b" ]
run = "cd ~/bin"
desc = "Go to the bin directory"

[[mgr.prepend_keymap]]
on = [ "g", "p" ]
run = "cd ~/projects"
desc = "Go to the projects directory"

[[mgr.prepend_keymap]]
on = [ "g", "d" ]
run = "cd ~/dls"
desc = "Go to the dls directory"

[[mgr.prepend_keymap]]
on = [ "g", "n" ]
run = "cd ~/notes"
desc = "Go to the notes directory"

[[mgr.prepend_keymap]]
on = [ "g", "f" ]
run = "cd /Volumes/t7/folders"
desc = "Go to the folders directory"

# [[manager.prepend_keymap]]
# on = [ "r" ]  
# run = "rename"
# run = 'nvim "$@" --block'
# desc = "Rename a file or directory"

# [[manager.prepend_keymap]]
# on = [ "q" ]
# run = "plugin projects --args=quit"
# desc = "Save last project and exit the process"

[[mgr.prepend_keymap]]
on = [ "P", "s" ]
run = "plugin projects --args=save"
desc = "Save current project"

[[mgr.prepend_keymap]]
on = [ "P", "l" ]
run = "plugin projects --args=load"
desc = "Load project"

[[mgr.prepend_keymap]]
on = [ "P", "P" ]
run = "plugin projects --args=load_last"
desc = "Load last project"

[[mgr.prepend_keymap]]
on = [ "P", "d" ]
run = "plugin projects --args=delete"
desc = "Delete project"

[[mgr.prepend_keymap]]
on = [ "P", "D" ]
run = "plugin projects --args=delete_all"
desc = "Delete all projects"

[[mgr.prepend_keymap]]
on   = [ "c", "a" ]
run  = "plugin compress"
desc = "Archive selected files"


